In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [54]:
x = np.array([1,2,3,4,5])
print('x is',x)

x is [1 2 3 4 5]


In [6]:
print(x[0])

1


In [53]:
x1 = np.arange(10)
print("x1 is ",x1)

x2 = np.arange(1, 10, 2)
print("x2 is ", x2)

x1 is  [0 1 2 3 4 5 6 7 8 9]
x2 is  [1 3 5 7 9]


In [11]:
# basic ways to fill np array
all_one = np.ones(4)   
print('all_one ', all_one) # [1 1 1 1]


all_zero = np.zeros(3) 
print('all_zero', all_zero) # [0 0 0]

all_one  [1. 1. 1. 1.]
all_zero [0. 0. 0.]


In [14]:
# Datatypes

print(x.dtype) #int

print(all_one.dtype) #float
print(all_zero.dtype) #float

int64
float64
float64


In [77]:
 x = np.ones(2, dtype=np.int64)
print(x)
print(x.dtype)

[1 1]
int64


In [75]:
x = np.linspace(0, 10, num=5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


#### Numpy arrays and lists? What's the deal?


Numpy arrays are fast!

In [60]:
import time

start = time.time()

normal_array = range(10000,100000)
sq_array = [i**2 for i in normal_array]

end = time.time()

print((end - start) * 1000 ,"milli seconds")
print(normal_array[4])
print(sq_array[4])

20.267486572265625 milli seconds
10004
100080016


In [67]:
import time

start = time.time()

np_array = np.arange(10000,100000)
np_sq_array = np_array ** 2 

end = time.time()

print((end - start) * 1000, "milli seconds")
print(np_array[4])
print(np_sq_array[4])

0.6086826324462891 milli seconds
10004
100080016


In [89]:
# Appending array element
x = np.array([1,3,4,5])
x = np.append(x,2)
print(x)

[1 3 4 5 2]


In [91]:
# Sorting an array
x = np.array([2, 1, 5, 3, 7, 4, 6, 8])
x = np.sort(x)
print(x)

[1 2 3 4 5 6 7 8]


In [94]:
# Sorting an array
x = np.array([2, 1, 5, 3, 7, 4, 6, 8])
x = np.sort(x)
print(x)

[1 2 3 4 5 6 7 8]


In [98]:
# Concatenate - merge 2 arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [103]:
# Indexing and slicing
x = np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[5 6 7 8 9]


In [107]:
print(x[5:8])

[5 6 7]


In [105]:
print(x[5:])

[5 6 7 8 9]


In [106]:
print(x[:5])

[0 1 2 3 4]


In [117]:
# Conditionally accesing elements

x = np.array([1,6,33, 50,99,78, 86, 2,9,6])

# I want numbers greater than 50

# Old way
y = []
for i in x:
    if i > 50:
        y.append(i)

np_y = np.array(y)
print(y)

[99, 78, 86]


In [118]:
# Numpy way
print(x[x > 50])

[99 78 86]


In [119]:
# I want numbers greater than 30 less than 60
print(x[(x > 30) & (x < 60)])
# Don't forget to put () for each condition

[33 50]


### Broadcasting

In [124]:
x = np.array([1,2,3])
# 
y = []
for i in x:
    y.append(i+10)

y = np.array(y)
print(y)

[11 12 13]


In [129]:
y = x + 10
print(y)

[11 12 13]


In [131]:
y = x * 100
print(y)

[100 200 300]


In [132]:
z = x + y
print(z)

[101 202 303]


In [135]:
# The above operations is different in lists
x = [1,2,3]
y = [4,5,6]
try:
    print(x+10)
except Exception as e:
    print(e)

try:
    print(x*100)
except Exception as e:
    print(e)

try:
    print(x+y)
except Exception as e:
    print(e)

can only concatenate list (not "int") to list
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


### Reshaping

![matrix](https://imgur.com/asbj5y6.png)

In [141]:
matrix = np.array([
    [1,2],
    [3,4],
    [5,6] 
])
print(matrix)
print('its shape is', matrix.shape)

[[1 2]
 [3 4]
 [5 6]]
its shape is (3, 2)


![matrix](https://imgur.com/c8embdg.png)

In [142]:
reshaped_matrix = matrix.reshape(2,3)
print(reshaped_matrix)
print('its shape is', reshaped_matrix.shape)

[[1 2 3]
 [4 5 6]]
its shape is (2, 3)


![Transpose](https://imgur.com/GfJiEi1.png)

In [144]:
print(matrix.transpose())

[[1 3 5]
 [2 4 6]]


### More useful

In [151]:
print('maximum element of matrix is')
print(matrix.max())

print('minimum element of matrix is')
print(matrix.min())

print('sum of all elements of matrix is')
print(matrix.sum())

maximum element of matrix is
6
minimum element of matrix is
1
sum of all elements of matrix is
21


In [153]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [ ]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
# https://towardsdatascience.com/matplotlib-tutorial-learn-basics-of-pythons-powerful-plotting-library-b5d1b8f67596